[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[start]
cmd = "node dist/server.js"
