[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-audit --no-fund"]

[phases.build]
cmds = ["node_modules/.bin/prisma generate", "node_modules/.bin/tsc --skipLibCheck || true"]

[start]
cmd = "node dist/server.js"
